export enum SYSTEM_ACCOUNT_TYPE {
    DEPOSIT_WITHDRAWALS="DEPOSIT_WITHDRAWALS",
    EARLY_WITHDRAWAL_FEES="EARLY_WITHDRAWAL_FEES",
    STAFF_ALLOWANCES="STAFF_ALLOWANCES"
  };

export const SYSTEM_ACCOUNT={
  DEPOSIT_WITHDRAWALS:"deposit_withdrawals",
  EARLY_WITHDRAWAL_FEES:"early_withdrawal_fees",
  STAFF_ALLOWANCES:"staff_allowances"
}